document.addEventListener("click", (doc, event) => {
  const p1 = document.getElementById("p1");
  if (p1) {
    p1.style.backgroundColor = "red";
  }
  const extensionContent = document.querySelector(".extension-content");
  if (extensionContent) {
    const insert = document.createElement("p");
    insert.innerHTML = "-- generated by extension";
    extensionContent.appendChild(insert);
  }

  chrome.runtime.sendMessage({ greeting: "hello" }, response => {
    console.log(response);
  });
});
